=== MrStevenFeldman/Robotics-Control-Sceme/Dalek Server/HardwareInfo.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="NAME" type="xs:string"/>
<xs:element name="ID">
	<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
</xs:element>

<xs:element name="MotorObj">
	<xs:complexType>
	<xs:sequence>
		<xs:element ref="NAME"/>
		<xs:element name="PWMA_PIN" type="xs:string" />
		<xs:element name="PWMB_PIN" type="xs:string" />
		<xs:element name="ENABLE_PIN" type="xs:string" />
		<xs:element name="CURRENT_PIN" type="xs:string" />
		<xs:element name="PWM_MIN" >
			<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction>
			</xs:simpleType>
		</xs:element>
		
	</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="Motor" >
	<xs:complexType>
	<xs:sequence>
		<xs:element ref="ID"/>
		<xs:element ref="MotorObj"/>
	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="MotorPair" >
	<xs:complexType>
	<xs:sequence>
		<xs:element ref="NAME"/>
		<xs:element ref="ID"/>
		<xs:element ref="MotorObj"/>
		<xs:element ref="MotorObj"/>
	</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="ServoObj">
	<xs:complexType>
	<xs:sequence>
		<xs:element ref="NAME"/>
		<xs:element name="PWM_PIN" type="xs:string" />
		
		<xs:element name="ANGLE_INIT" >
			<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="360"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
		<xs:element name="ANGLE_MAX" >
			<xs:simpleType><xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="360"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
		<xs:element name="ANGLE_MIN" >
			<xs:simpleType><xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="360"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
		<xs:element name="PWM_MAX" >
			<xs:simpleType><xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
		<xs:element name="PWM_MIN" >
			<xs:simpleType><xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>	
</xs:element>

<xs:element name="Servo" >
	<xs:complexType>
	<xs:sequence>
		<xs:element ref="ID"/>
		<xs:element ref="ServoObj"/>
	</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="ServoPair" >
	<xs:complexType>
	<xs:sequence>
		<xs:element ref="NAME"/>
		<xs:element ref="ID"/>
		<xs:element ref="ServoObj"/>
		<xs:element ref="ServoObj"/>
	</xs:sequence>
	</xs:complexType>
</xs:element>



<xs:element name="Stepper">
	<xs:complexType>
	<xs:sequence>
		<xs:element ref="NAME"/>
		<xs:element name="DIR_PIN" type="xs:string" />
		<xs:element name="PINS" type="xs:string" />
		<xs:element name="PIN1" type="xs:string" />
		<xs:element name="PIN2" type="xs:string" />
		<xs:element name="PIN3" type="xs:string" />
		<xs:element name="PIN4" type="xs:string" />
		<xs:element name="EnablePin" type="xs:string" />
		<xs:element name="MAX_SPEED" >
			<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
		<xs:element name="ACCELERATION" >
			<xs:simpleType><xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
		
		<xs:element name="MIN_POS" >
			<xs:simpleType><xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
		<xs:element name="MAX_POS" >
			<xs:simpleType><xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
		
		<xs:element name="INIT_POS" >
			<xs:simpleType><xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
			</xs:restriction></xs:simpleType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>	
</xs:element>

<xs:element name="HardwareInfo">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="DeviceList">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="Servo" maxOccurs="unbounded" minOccurs="0"/>
						<xs:element ref="ServoPair" maxOccurs="unbounded" minOccurs="0"/>
						<xs:element ref="Motor" maxOccurs="unbounded" minOccurs="0"/>
						<xs:element ref="MotorPair" maxOccurs="unbounded" minOccurs="0"/>
						<xs:element ref="Stepper" maxOccurs="unbounded" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== MrStevenFeldman/Robotics-Control-Sceme/Dalek Server/HardWareInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<HardwareInfo
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="HardwareInfo.xsd">
	<DeviceList>
		
	 
		<MotorPair>
			<NAME>DriveMotors</NAME>
			<ID>1</ID>
			
			<MotorObj>
				<NAME>leftmotor</NAME>
		
				<PWMA_PIN>P9_14</PWMA_PIN>
				<PWMB_PIN>P9_16</PWMB_PIN>
				<ENABLE_PIN>P8_7</ENABLE_PIN>
				<CURRENT_PIN>P9_39</CURRENT_PIN>
			</MotorObj>
	
			<MotorObj>
				<NAME>rightmotor</NAME>
			
				<PWMA_PIN>P8_19</PWMA_PIN>
				<PWMB_PIN>P8_13</PWMB_PIN>
				<ENABLE_PIN>P8_7</ENABLE_PIN>
				<CURRENT_PIN>P9_40</CURRENT_PIN>
	
			</MotorObj>
			
		</MotorPair>

		<Servo>
			<ID>2</ID>
			<ServoObj>
				<NAME>EyeStalk</NAME>
				<PWM_PIN>I_0x70_4</PWM_PIN>
				<PWM_MAX>100</PWM_MAX>
				<PWM_MIN>0</PWM_MIN>
				<ANGLE_INIT>0</ANGLE_INIT>
				<ANGLE_MIN>0</ANGLE_MIN>
				<ANGLE_MAX>90</ANGLE_MAX>
				
			</ServoObj>
		</Servo>
		<ServoPair>
			<ID>3</ID>
			<NAME>PlungerBox</NAME>
			<ServoObj>
				<NAME>Left</NAME>
				<PWM_PIN>I_0x70_2</PWM_PIN>
				<PWM_MAX>100</PWM_MAX>
				<PWM_MIN>0</PWM_MIN>
				<ANGLE_INIT>0</ANGLE_INIT>
				<ANGLE_MIN>0</ANGLE_MIN>
				<ANGLE_MAX>360</ANGLE_MAX>
			</ServoObj>
			<ServoObj>
				<NAME>Right</NAME>
				<PWM_PIN>I_0x70_3</PWM_PIN>
				<PWM_MAX>100</PWM_MAX>
				<PWM_MIN>0</PWM_MIN>
				<ANGLE_INIT>0</ANGLE_INIT>
				<ANGLE_MIN>0</ANGLE_MIN>
				<ANGLE_MAX>360</ANGLE_MAX>
			</ServoObj>
		</ServoPair>
		<ServoPair>
			<ID>4</ID>
			<NAME>GunBox</NAME>
			<ServoObj>
				<NAME>Left</NAME>
				<PWM_PIN>I_0x70_0</PWM_PIN>
				<PWM_MAX>100</PWM_MAX>
				<PWM_MIN>0</PWM_MIN>
				<ANGLE_INIT>0</ANGLE_INIT>
				<ANGLE_MIN>0</ANGLE_MIN>
				<ANGLE_MAX>360</ANGLE_MAX>
				
			</ServoObj>
			<ServoObj>
				<NAME>Right</NAME>
				<PWM_PIN>I_0x70_1</PWM_PIN>
				<PWM_MAX>100</PWM_MAX>
				<PWM_MIN>0</PWM_MIN>
				<ANGLE_INIT>0</ANGLE_INIT>
				<ANGLE_MIN>0</ANGLE_MIN>
				<ANGLE_MAX>360</ANGLE_MAX>
			</ServoObj>
		</ServoPair>
		
		<Servo>
			<ID>5</ID>
			<ServoObj>
				<NAME>IrisDiaphraph</NAME>
				<PWM_PIN>I_0x70_5</PWM_PIN>
				<PWM_MAX>100</PWM_MAX>
				<PWM_MIN>0</PWM_MIN>
				<ANGLE_INIT>0</ANGLE_INIT>
				<ANGLE_MIN>0</ANGLE_MIN>
				<ANGLE_MAX>90</ANGLE_MAX>
				
			</ServoObj>
		</Servo>
		<!--<RGBLED>
			<ID>6</ID>
			<NAME>EyeLED</NAME>
			<PWM_PIN>I_0x70_6</PWM_PIN>
			<PWM_MAX>100</PWM_MAX>
			<PWM_MIN>0</PWM_MIN>
			<PWM_INIT>0</PWM_INIT>
		</RGBLED>
		<RGBLED>
			<ID>7</ID>
			<NAME>FenderLed</NAME>
			<PWM_PIN>I_0x70_7</PWM_PIN>
			<PWM_MAX>100</PWM_MAX>
			<PWM_MIN>0</PWM_MIN>
			<PWM_INIT>0</PWM_INIT>
		</RGBLED> -->
		
		<Stepper>
			<ID>8</ID>
			<NAME>Dome</NAME>
			<PINS>2</PINS>
			<PIN1>15</PIN1>
			<PIN2>45</PIN2>
			<MAX_SPEED></MAX_SPEED>
			<ACCELERATION></ACCELERATION>
			<INIT_POS></INIT_POS>
			<MAX_POS></MAX_POS>
			<MIN_POS></MIN_POS>
		</Stepper>
		<Stepper>
			<ID>9</ID>
			<NAME>Shoulder</NAME>
			<PINS>2</PINS>
			<PIN1>14</PIN1>
			<PIN2>44</PIN2>
			<MAX_SPEED></MAX_SPEED>
			<ACCELERATION></ACCELERATION>
			<INIT_POS></INIT_POS>
			<MAX_POS></MAX_POS>
			<MIN_POS></MIN_POS>
		</Stepper>
		
	</DeviceList>
	
	
</HardwareInfo>
